name: "cosign"
description: "Setups cosign with a custom TUF mirror"

inputs:
  version:
    description: "Cosign version to install"
    default: "v2.0.2"
  tufRoot:
    description: "TUF trusted root file"
    default: ""
  tufMirror:
    description: "TUF Mirror URL"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: ${{ inputs.version }}
    - name: Initialize Cosign
      if: inputs.tufMirror != '' && inputs.tufRoot != ''
      shell: bash
      run: |
        echo "tufMirror: '${{ inputs.tufMirror }}'"
        echo "tufRoot: '${{ inputs.tufRoot }}'"
        cosign initialize --mirror ${{ inputs.tufMirror }} --root ${{ inputs.tufRoot }}
