name: "cosign"
description: "Setups cosign with a custom TUF mirror"

inputs:
  version:
    description: "Cosign version to install"
    default: "v2.2.3"
  tufRoot:
    description: "TUF trusted root file"
    default: ""
  tufMirror:
    description: "TUF Mirror URL"
    default: ""
  workingDirectory:
    description: "Working directory used when running cosign initialize"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3
      with:
        cosign-release: ${{ inputs.version }}
    - name: Initialize Cosign
      if: inputs.tufMirror != '' && inputs.tufRoot != ''
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        cosign initialize --mirror ${{ inputs.tufMirror }} --root ${{ inputs.tufRoot }}
