name: "config"
description: "Loads liatrio/gh-trusted-builds-workflows configuration"

inputs:
  acrName:
    description: "Azure container registry instance name"
  client:
    description: "Service principal client id"
  tenant:
    description: "Azure tenant id"
  subscription:
    description: "Azure subscription id"

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client }}
        tenant-id: ${{ inputs.tenant }}
        subscription-id: ${{ inputs.subscription }}

    - name: Azure Account
      shell: bash
      run: az account show

    - name: Authenticate to ACR
      shell: bash
      run: az acr login -n ${{ inputs.acrName }}
