name: Demo Deploy

on:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"
      k3dVersion:
        type: string
        description: "k3s version"
        default: "v5.4.9"
      policyControllerVersion:
        type: string
        description: "Policy controller Helm chart version"
        default: "0.5.7"
      fulcioUrl:
        description: "Sigstore Fulcio URL. Defaults to the production public good instance"
        default: "https://fulcio.sigstore.dev"
        type: string
      rekorUrl:
        description: "Sigstore Rekor URL. Defaults to the production public good instance"
        default: "https://rekor.sigstore.dev"
        type: string
      tufMirror:
        description: "cosign TUF root mirror URL. If not specified, cosign initialize will not be invoked"
        default: ""
        type: string
      tufRoot:
        description: "cosign TUF initial trusted root. If not specified, cosign initialize will not be invoked"
        default: ""
        type: string


jobs:
  deploy:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
         version: v3.12.0

      - name: Install k3s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo k3d-io/k3d \
            --pattern k3d-linux-amd64 \
            ${{ inputs.k3dVersion }}
          chmod +x k3d-linux-amd64
          mkdir -p $HOME/.bin/k3d
          mv k3d-linux-amd64 $HOME/.bin/k3d/k3d
          echo "$HOME/.bin/k3d" >> $GITHUB_PATH

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Cluster
        run: |
          k3d cluster create --agents 1 --no-lb --wait demo

      - name: Import Image
        run: |
          docker pull ghcr.io/${{ github.repository }}@${{ inputs.digest }}
          docker save -o image.tar ghcr.io/${{ github.repository }}@${{ inputs.digest }}
          k3d image import --keep-tarball=false --cluster demo image.tar
          ls -la

      - name: Add Sigstore Helm Repo
        run: |
          helm --version
          helm repo add sigstore https://sigstore.github.io/helm-charts
          helm repo update

      - name: Deploy Policy Controller
        run: |
          helm install \
            --wait \
            --create-namespace \
            -n policy-controller \
            --version ${{ inputs.policyControllerVersion }} \
            policy-controller sigstore/policy-controller

      - name: Debug
        run: |
          kubectl get ns
          kubectl -n policy-controller get all
