on:
  workflow_dispatch:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"
      fulcioUrl:
        description: "Sigstore Fulcio URL. Defaults to the production public good instance"
        default: "https://fulcio.sigstore.dev"
      rekorUrl:
        description: "Sigstore Rekor URL. Defaults ot the production public good instance"
        default: "https://rekor.sigstore.dev"
      token:
        description: "GitHub token - used to push to GitHub Container Registry and download release assets"
      tufMirror:
        description: "cosign TUF root mirror URL. If not specified, cosign initialize will not be invoked"
        default: ""
      tufRoot:
        description: "cosign TUF initial trusted root. If not specified, cosign initialize will not be invoked"
        default: ""
      vsaAppVersion:
        description: "liatrio/gh-trusted-builds-vsa application version"
        default: "1.0.0"

env:
  GITHUB_ACTIONS_ISSUER: "https://token.actions.githubusercontent.com"

jobs:
  metadata:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.workflow.outputs.ref }}
    steps:
      - name: Determine Workflow Ref
        id: workflow
        uses: liatrio/gh-trusted-builds-workflows/.github/actions/workflow-ref@main

  verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [metadata]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cosign Setup
        uses: liatrio/gh-trusted-builds-workflows/.github/actions/cosign@main
        with:
          tufRoot: ${{ inputs.tufRoot }}
          tufMirror: ${{ inputs.tufMirror }}

      - name: Install VSA Application
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        run: |
          gh release download \
            --repo liatrio/gh-trusted-builds-vsa \
            --pattern "gh-trusted-builds-vsa_${VSA_APP_VERSION}_linux_amd64.tar.gz" "v${VSA_APP_VERSION}"
          tar xvf "gh-trusted-builds-vsa_${VSA_APP_VERSION}_linux_amd64.tar.gz"
          sudo cp ./vsa /usr/local/bin/vsa
          vsa --help

      - name: Verify Attestations
        run: |
          cosign tree ghcr.io/${{ github.repository }}@${{ inputs.digest }}@${{ inputs.digest }} 
          
          cosign verify-attestation \
            --rekor-url ${{ inputs.rekorUrl }} \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-github-workflow-repository ${{ github.repository }} \
            --certificate-identity https://github.com/liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml@${{ needs.metadata.outputs.ref }} \
            --type vuln \
            ghcr.io/${{ github.repository }}@${{ inputs.digest }}

      - name: Create Verification Summary Attestation
        run: |
          vsa \
          --artifact-uri ghcr.io/${{ github.repository }}@${{ inputs.digest }} \
          --artifact-digest ${{ inputs.digest }} \
          --commit-sha ${{ github.sha }} \
          --policy-version "v1.1.1" \
          --verifier-id ${{ github.workflow_ref }} \
          --fulcio-url ${{ inputs.fulcioUrl }}
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
