name: Policy Verification

on:
  workflow_call:
    inputs:
      attestorVersion:
        description: "liatrio/gh-trusted-builds-attestations version"
        default: "1.1.4"
        type: string
      cosignVersion:
        description: "Sigstore cosign version"
        default: "v2.0.2"
        type: string
      digest:
        type: string
        required: true
        description: "Docker image digest"
      fulcioUrl:
        description: "Sigstore Fulcio URL. Defaults to the production public good instance"
        default: "https://fulcio.sigstore.dev"
        type: string
      rekorUrl:
        description: "Sigstore Rekor URL. Defaults to the production public good instance"
        default: "https://rekor.sigstore.dev"
        type: string
      tufMirror:
        description: "cosign TUF root mirror URL. If not specified, cosign initialize will not be invoked"
        default: ""
        type: string
      tufRoot:
        description: "cosign TUF initial trusted root. If not specified, cosign initialize will not be invoked"
        default: ""
        type: string

jobs:
  detect-workflow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to grab job_workflow_ref information
    outputs:
      repository: ${{ steps.detect.outputs.repository }}
      ref: ${{ steps.detect.outputs.ref }}
      workflow: ${{ steps.detect.outputs.workflow }}
    steps:
      - name: Detect the repository and ref
        id: detect
        uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow-js@0779f7bec68e2bf54a7b0a32bf4763f25ab29702 # v1.6.0

  verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to sign attestations
      contents: read # for reading local TUF root.json file
      packages: write # required to upload attestations to GHCR
    needs: [detect-workflow]
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout App Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          path: app

      - name: Checkout Workflows Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          repository: ${{ needs.detect-workflow.outputs.repository }}
          ref: ${{ needs.detect-workflow.outputs.ref }}
          path: gh-trusted-builds-workflows
          persist-credentials: false

      - name: Cosign Setup
        uses: ./gh-trusted-builds-workflows/.github/actions/cosign
        with:
          tufRoot: ${{ inputs.tufRoot }}
          tufMirror: ${{ inputs.tufMirror }}
          version: ${{ inputs.cosignVersion }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Attestations
        run: |
          cosign tree ghcr.io/${{ github.repository }}@${{ inputs.digest }}

      - name: Attestor Install
        uses: ./gh-trusted-builds-workflows/.github/actions/attestor
        with:
          version: ${{ inputs.attestorVersion }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Verification Summary Attestation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          attestation vsa \
            --artifact-uri ghcr.io/${{ github.repository }} \
            --artifact-digest ${{ inputs.digest }} \
            --policy-url "https://github.com/liatrio/gh-trusted-builds-policy/releases/download/v1.4.0/bundle.tar.gz" \
            --verifier-id ${{ github.server_url }}/${{ needs.detect-workflow.outputs.repository }}/${{ needs.detect-workflow.outputs.workflow }}@${{ needs.detect-workflow.outputs.ref }} \
            --fulcio-url ${{ inputs.fulcioUrl }} \
            --rekor-url ${{ inputs.rekorUrl }}
