name: Policy Verification

on:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"
      environment:
        description: "Name of the Sigstore environment to use. Should be one of [staging, production]"
        default: "production"
        type: string

jobs:
  detect-workflow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to grab job_workflow_ref information
    outputs:
      repository: ${{ steps.detect.outputs.repository }}
      ref: ${{ steps.detect.outputs.ref }}
      workflow: ${{ steps.detect.outputs.workflow }}
    steps:
      - name: Detect the repository and ref
        id: detect
        uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow-js@e55b76ce421082dfa4b34a6ac3c5e59de0f3bb58 # v1.7.0

  verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to sign attestations
      contents: read # for reading local TUF root.json file
      packages: write # required to upload attestations to GHCR
    needs: [detect-workflow]
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout App Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          path: app

      - name: Checkout Workflows Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          repository: ${{ needs.detect-workflow.outputs.repository }}
          ref: ${{ needs.detect-workflow.outputs.ref }}
          path: gh-trusted-builds-workflows
          persist-credentials: false

      - name: Configuration
        id: config
        uses: ./gh-trusted-builds-workflows/.github/actions/config
        with:
          environment: ${{ inputs.environment }}

      - name: Cosign Setup
        uses: ./gh-trusted-builds-workflows/.github/actions/cosign
        with:
          tufRoot: ${{ steps.config.outputs.tufRoot }}
          tufMirror: ${{ steps.config.outputs.tufMirror }}
          version: ${{ steps.config.outputs.cosignVersion }}
          workingDirectory: ./gh-trusted-builds-workflows

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Attestations
        run: |
          cosign tree ghcr.io/${{ github.repository }}@${{ inputs.digest }}

      - name: Attestor Install
        uses: ./gh-trusted-builds-workflows/.github/actions/attestor
        with:
          version: ${{ steps.config.outputs.attestorVersion }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Verification Summary Attestation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          attestation vsa \
            --artifact-uri ghcr.io/${{ github.repository }} \
            --artifact-digest ${{ inputs.digest }} \
            --policy-url "../gh-trusted-builds-workflows/policies/governance" \
            --policy-query 'data.governance.always_allow' \
            --verifier-id ${{ github.server_url }}/${{ needs.detect-workflow.outputs.repository }}/${{ needs.detect-workflow.outputs.workflow }}@${{ needs.detect-workflow.outputs.ref }} \
            --fulcio-url ${{ steps.config.outputs.fulcioUrl }} \
            --rekor-url ${{ steps.config.outputs.rekorUrl }}
