on:
  workflow_dispatch:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"

env:
  AZURE_CLIENT_ID: "58162388-16a0-4c7c-91f4-bdfc1ce2cd69"
  AZURE_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
  AZURE_SUBSCRIPTION_ID: "3e16852e-8399-4c16-b246-16bf46bc3747"
  ACR_NAME: "agplatformrnim"
  GITHUB_ACTIONS_ISSUER: "https://token.actions.githubusercontent.com"
  REKOR_HOST: "rekor-ham0vei9.ngrok.io"
  FULCIO_HOST: "fulcio-ham0vei9.ngrok.io"
  TUF_ROOT_MIRROR: "https://agtufrootcrml.blob.core.windows.net/tuf-root"

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'az login'
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: 'az account show'
        run: |
          az account show

      - name: Authenticate to ACR
        run: az acr login -n "${ACR_NAME}"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.0.2'

      - name: Initialize Cosign
        run: |
          cosign initialize --mirror ${TUF_ROOT_MIRROR} --root root.json 

      - name: Install Rekor CLI
        run: |
          curl -Lo rekor-cli https://github.com/sigstore/rekor/releases/download/v1.1.0/rekor-cli-linux-amd64
          chmod +x rekor-cli
          sudo cp rekor-cli /usr/local/bin/.
          rekor-cli version

      - name: Verify Attestations
        env:
          AZURE_AUTH_METHOD: "cli"
          SIGSTORE_REKOR_PUBLIC_KEY: ./rekor.pub
        run: |
          cosign tree ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }} 
          
          cosign verify-attestation \
            --rekor-url "https://${REKOR_HOST}" \
            --certificate-oidc-issuer "${GITHUB_ACTIONS_ISSUER}" \
            --certificate-github-workflow-repository ${{ github.repository }} \
            --certificate-identity https://github.com/liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml@refs/heads/keyless \
            --type vuln \
            ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }}

      - name: Collect Attestations
        run: |
          echo "Collect artifact attestations"
          rekor-cli search \
            --rekor_server "https://${REKOR_HOST}" \
            --sha ${{ inputs.digest }} \
            --format json > artifact.json
          cat artifact.json
          
          echo "Collect source attestations"
          rekor-cli search \
            --rekor_server "https://${REKOR_HOST}" \
            --sha ${GITHUB_SHA} \
            --format json > source.json
          cat source.json

      - name: Sign Artifact
        env:
          AZURE_AUTH_METHOD: "cli"
        run: |
          cosign sign \
            -a liatr.io/github-actions-run-link='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
            -a liatr.io/signed-off-by=security-team \
            --output-signature image.sig \
            --rekor-url "https://${REKOR_HOST}" \
            --fulcio-url "https://${FULCIO_HOST}" \
            -y ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }}

      - name: Upload Signatures
        uses: actions/upload-artifact@v3
        with:
          name: security.sig
          path: |
            image.sig
