name: Rekor Monitor

on:
 schedule:
   - cron: '0 * * * *' # hourly

jobs:
  run-consistency-proof:
    permissions:
      contents: read
      issues: write
      id-token: write
    uses: sigstore/rekor-monitor/.github/workflows/reusable_monitoring.yml@d7458ab1ec52524bf11057d4c2e38bf07b6a5a5c
    with:
      file_issue: true
      artifact_retention_days: 14
      identities: |
        certIdentities:
          - certSubject: ^${{ github.server_url }}/${{ github.repository }}/\.github/workflows/build-and-push\.yaml@.*
            issuers:
              - https://token.actions.githubusercontent.com
          - certSubject: ^${{ github.server_url }}/${{ github.repository }}/\.github/workflows/scan-image\.yaml@.*
            issuers:
              - https://token.actions.githubusercontent.com
          - certSubject: ^${{ github.server_url }}/${{ github.repository }}/\.github/workflows/policy-verification\.yaml@.*
            issuers:
              - https://token.actions.githubusercontent.com
