name: Rekor Monitor

on:
  push:
    branches:
      - fix-rekor-monitor
#  schedule:
#    - cron: '0 * * * *' # hourly

env:
  GITHUB_ACTIONS_ISSUER: "https://token.actions.githubusercontent.com"

jobs:
  run-consistency-proof:
    permissions:
      contents: read
      issues: write
      id-token: write
    uses: sigstore/rekor-monitor/.github/workflows/reusable_monitoring.yml@main
    with:
      file_issue: true
      artifact_retention_days: 14
      identities: |
        certIdentities:
          - certSubject: ^${{ github.server_url }}/${{ github.repository }}/.\github/workflows/build-and-push\.yaml@.*
            issuers:
              - ${{ env.GITHUB_ACTIONS_ISSUER }}
          - certSubject: ^${{ github.server_url }}/${{ github.repository }}/.\github/workflows/scan-image\.yaml@.*
            issuers:
              - ${{ env.GITHUB_ACTIONS_ISSUER }}
          - certSubject: ^${{ github.server_url }}/${{ github.repository }}/.\github/workflows/policy-verification\.yaml@.*
            issuers:
              - ${{ env.GITHUB_ACTIONS_ISSUER }}
