name: Release Workflows
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18
      - name: Setup Semantic Release
        run: npm install -g semantic-release -D
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ github.token }}