name: Release Workflows
on:
  push:
    branches:
      - main

jobs:
  integration:
    uses: ./.github/workflows/integration-tests.yaml
    with:
      concurrencyGroupTag: ${{ github.sha }} # always run, so releases are not skipped.
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs:
      - integration
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: .nvmrc
      - name: Setup Semantic Release
        run: npm install -g semantic-release -D
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ github.token }}