on:
  workflow_dispatch:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"

env:
  AZURE_CLIENT_ID: "48fbd2e1-8375-4c05-9957-f5c6c702181f"
  AZURE_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
  AZURE_SUBSCRIPTION_ID: "3e16852e-8399-4c16-b246-16bf46bc3747"
  AZURE_KEYVAULT_NAME: "ag-poc-platform-c2wn"
  ACR_NAME: "agplatformrnim"
  INGRESS_CA: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkVENDQVJ5Z0F3SUJBZ0lRVG95NnBId0Rwb2R2UnFuRFZsMkY4REFLQmdncWhrak9QUVFEQWpBYk1Sa3cKRndZRFZRUURFeEJ0ZVMxelpXeG1jMmxuYm1Wa0xXTmhNQjRYRFRJek1EVXdNakF5TURNd09Wb1hEVEl6TURjegpNVEF5TURNd09Wb3dHekVaTUJjR0ExVUVBeE1RYlhrdGMyVnNabk5wWjI1bFpDMWpZVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQlB3SjdWREl6bExjR2dBZTgwODJjRDhiLzNqZ3V2S0o5U0xXb1F0TDl4L1kKcDNYaTdKNDBkSEFicFV0QUJlaEhOWjhXUXJ0V0h3SVFNOE44SUtBTlk5R2pRakJBTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTRjZjRVI1SUlnZGVvaE93U2pzNmRKCm9aZnIxakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUVBalZwQk84Nnc4alEyTk9tRTZqQml4L2xBbWp0SUVMOCsKcDBMTEp0d1N2Y2tDSDFEVnh1QVJidVhFS05RTUFrdTRHSktQWU9YWEtIY0hzbWdvMW9sN3BzST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  PLATFORM_TEAM_PUB_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFaUpmamtBY1FBZDJ1L1ZDeUpiOXF4bVV4d0pDYgoyZlBZZ1JrekdKbEYySUdHbnUrRWJycEo3SU1jaXN2cXYxOUE1cFVUazZCRXAxWnl0VzRVMmYxL3FBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  SECURITY_TEAM_PUB_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFQjFDNURoOGxsSzhxSnpNcFMvN3FINUR3dDZGMgp6SDlPNGNrYjVkSTYxQnF3RzZJbENBcmt1bkc0Vi9PcEltQU04TEtXTGtnYjVzV2dPbkFheU5VWlFnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  REKOR_HOST: "rekor.sec-guild-dev.private.northcentralus.azmk8s.io"
  TAILSCALE_SECRET_NAME: "tailscale-authkey"

jobs:
  verify:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Account
        run: az account show

      - name: Authenticate to ACR
        run: az acr login -n "${ACR_NAME}"

      - name: Retrieve Tailscale Key
        id: tailscale-auth
        run: |
          authKey=$(az keyvault secret show --name "${TAILSCALE_SECRET_NAME}" --vault-name "${AZURE_KEYVAULT_NAME}" --query value -o tsv)
          echo "::add-mask::${authKey}"
          echo "authkey=${authKey}" >> $GITHUB_OUTPUT

      - name: Setup Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ steps.tailscale-auth.outputs.authkey }}

      - name: Trust Ingress CA Certificate
        run: |
          printf "${INGRESS_CA}" | base64 -d > ca.crt
          sudo cp ca.crt /usr/local/share/ca-certificates
          sudo update-ca-certificates

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.0.0'
      - name: Download Rekor Public Key
        run: |
          curl -o rekor.pub "https://${REKOR_HOST}/api/v1/log/publicKey"

      - name: Verify Platform Team Signature
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: ./rekor.pub
        run: |
          printf "${PLATFORM_TEAM_PUB_KEY}" | base64 -d > platform.pub

          cosign verify \
              --rekor-url "https://${REKOR_HOST}" \
              --key platform.pub \
              -a liatr.io/built-from=liatrio/gh-trusted-builds-app \
              -a liatr.io/built-by='liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml' \
              -a liatr.io/signed-off-by=platform-team \
              ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }}

          rm platform.pub

      - name: Verify Security Team Signature
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: ./rekor.pub
        run: |
          printf "${SECURITY_TEAM_PUB_KEY}" | base64 -d > security.pub

          cosign verify \
            --rekor-url "https://${REKOR_HOST}" \
            --key security.pub \
            -a liatr.io/scanned-by='liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml' \
            -a liatr.io/signed-off-by=security-team \
            ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }}

          rm security.pub
