on:
  workflow_dispatch:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"

env:
  AZURE_CLIENT_ID: "48fbd2e1-8375-4c05-9957-f5c6c702181f"
  AZURE_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
  AZURE_SUBSCRIPTION_ID: "3e16852e-8399-4c16-b246-16bf46bc3747"
  ACR_NAME: "agplatformrnim"
  GITHUB_ACTIONS_ISSUER: "https://token.actions.githubusercontent.com"
  REKOR_HOST: "rekor-ham0vei9.ngrok.io"
  FULCIO_HOST: "fulcio-ham0vei9.ngrok.io"
  TUF_ROOT_MIRROR: "https://agtufrootcrml.blob.core.windows.net/tuf-root"

jobs:
  verify:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Account
        run: az account show

      - name: Authenticate to ACR
        run: az acr login -n "${ACR_NAME}"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.0.2'

      - name: Initialize Cosign
        run: |
          cosign initialize --mirror ${TUF_ROOT_MIRROR} --root root.json          

      - name: Verify Platform Team Signature
        run: |
          cosign verify \
              --rekor-url "https://${REKOR_HOST}" \
              --certificate-oidc-issuer "${GITHUB_ACTIONS_ISSUER}" \
              --certificate-github-workflow-repository ${{ github.repository }}
              --certificate-identity https://github.com/liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml@refs/heads/keyless
              -a liatr.io/built-from=liatrio/gh-trusted-builds-app \
              -a liatr.io/signed-off-by=platform-team \
              ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }}

      - name: Verify Security Team Signature
        env:
          SIGSTORE_REKOR_PUBLIC_KEY: ./rekor.pub
        run: |
          cosign verify \
            --rekor-url "https://${REKOR_HOST}" \
            --certificate-oidc-issuer "${GITHUB_ACTIONS_ISSUER}" \
            --certificate-github-workflow-repository ${{ github.repository }}
            --certificate-identity https://github.com/liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml@refs/heads/keyless
            -a liatr.io/signed-off-by=security-team \
            ${{ env.ACR_NAME }}.azurecr.io/${{ github.repository }}@${{ inputs.digest }}
