on:
  workflow_call:
    inputs:
      digest:
        type: string
        required: true
        description: "Docker image digest"
      rekorUrl:
        description: "Sigstore Rekor URL. Defaults to the production public good instance"
        default: "https://rekor.sigstore.dev"
        type: string
      tufMirror:
        description: "cosign TUF root mirror URL. If not specified, cosign initialize will not be invoked"
        default: ""
        type: string
      tufRoot:
        description: "cosign TUF initial trusted root. If not specified, cosign initialize will not be invoked"
        default: ""
        type: string

jobs:
  metadata:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.workflow.outputs.ref }}
    steps:
      - name: Determine Workflow Ref
        id: workflow
        uses: liatrio/gh-trusted-builds-workflows/.github/actions/workflow-ref@open-source

  verify:
    permissions:
      id-token: write
      contents: read
      packages: read
    runs-on: ubuntu-latest
    needs: [metadata]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cosign Setup
        uses: liatrio/gh-trusted-builds-workflows/.github/actions/cosign@open-source
        with:
          tufRoot: ${{ inputs.tufRoot }}
          tufMirror: ${{ inputs.tufMirror }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Image Built From Platform Team Workflow
        run: |
          cosign verify \
              --rekor-url ${{ inputs.rekorUrl }} \
              --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
              --certificate-github-workflow-repository ${{ github.repository }} \
              --certificate-identity https://github.com/liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml@${{ needs.metadata.outputs.ref }} \
              --annotations liatr.io/signed-off-by=platform-team \
              ghcr.io/${{ github.repository }}@${{ inputs.digest }}
